mode = "dark"
accent = "#b891ff"
selection = "#3c2859"
muted = "#96909f"
background = "#07070a"
dark_background = "#050508"
darker_background = "#030305"
lighter_background = "#17151d"
foreground = "#f4f1f7"
dark_foreground = "#96909f"
light_foreground = "#d3cadf"
bright_foreground = "#ffffff"
red = "#ff496c"
yellow = "#e6dc86"
orange = "#ff673d"
green = "#c7ff35"
cyan = "#53deff"
blue = "#91a5ff"
magenta = "#b891ff"
brown = "#b68b71"
bright_red = "#ff7893"
bright_yellow = "#f3ebb1"
bright_green = "#dbff86"
bright_cyan = "#9aecff"
bright_blue = "#b5c2ff"
bright_magenta = "#d5bbff"
