'use strict';
const $ = id => document.getElementById(id);
let config = {}, history = [], chatBusy = false, cpuSamples = [], latestMachine = null;
let focus = JSON.parse(localStorage.getItem('quan-focus') || 'null') || {remaining:1500,end:null};
const gib = n => (n/1073741824).toFixed(1);
const date = n => n ? new Date(n*1000).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}) : 'Date unavailable';
const toast = text => { $('toast').textContent=text; $('toast').hidden=false; clearTimeout(toast.timer); toast.timer=setTimeout(()=>$('toast').hidden=true,5000); };
async function api(path, body) { const res = await fetch('/api/'+path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}); const data=await res.json(); if(!res.ok)throw Error(data.error||'Something went wrong'); return data; }
function node(tag, text, cls) {const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(cls)el.className=cls;return el;}
function chart(){const canvas=$('cpu-chart'),r=canvas.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=r.width*d;canvas.height=r.height*d;const c=canvas.getContext('2d');c.scale(d,d);c.strokeStyle='#b891ff';c.lineWidth=1.7;c.beginPath();cpuSamples.forEach((v,i)=>{const x=i*r.width/Math.max(1,cpuSamples.length-1),y=r.height-3-(v/100)*(r.height-6);i?c.lineTo(x,y):c.moveTo(x,y)});c.stroke();}
async function refreshMachine(){try{const d=await api('machine');latestMachine=d;$('connection').textContent='● Live · updated every 5 seconds';$('cpu').textContent=d.cpu===null?'—':Math.round(d.cpu)+'%';$('temp').textContent=d.temperature===null?'Sensor unavailable':Math.round(d.temperature)+'°C';if(d.cpu!==null){cpuSamples.push(d.cpu);if(cpuSamples.length>40)cpuSamples.shift();chart()};$('ram').textContent=gib(d.ramUsed)+' GB';$('ram-total').textContent='of '+gib(d.ramTotal)+' GB';$('ram-bar').value=100*d.ramUsed/d.ramTotal;$('disk').textContent=Math.round(d.diskFree/1073741824)+' GB';$('disk-bar').value=100*(1-d.diskFree/d.diskTotal);$('uptime').textContent='Up '+Math.floor(d.uptime/3600)+'h '+Math.floor(d.uptime%3600/60)+'m';$('agent-count').textContent=d.agents.length+' processes';$('process-list').replaceChildren(...(d.agents.length?d.agents.map(a=>node('span',a.name+' · '+a.pid,'process-tag')):[node('span','No agent processes running')]))}catch(e){$('connection').textContent='Disconnected · last readings retained'}}
async function refreshModels(){try{const d=await api('models');$('model-status').textContent=!d.online?'Offline':d.models.length?'Ready':'Getting ready';$('model-detail').textContent=!d.online?'Ollama is not running':d.models.length?d.models.length+' downloaded model'+(d.models.length===1?'':'s')+' · '+d.running.length+' loaded':'Waiting for the model download';const current=$('model').value;if(JSON.stringify(d.models.map(m=>m.name))!==$('model').dataset.models){$('model').replaceChildren(...(d.models.length?d.models.map(m=>{const o=node('option',m.name);o.value=m.name;return o}):[node('option','No local models yet')]));$('model').dataset.models=JSON.stringify(d.models.map(m=>m.name));if(d.models.some(m=>m.name===current))$('model').value=current;}$('send').disabled=chatBusy||!d.models.length;const ready=d.models.some(m=>m.name==='qwen3.5:4b');$('local-launch').disabled=!ready;$('local-launch-note').textContent=ready?'Codex with your local Qwen model':'Waiting for the local model';}catch(e){$('model-status').textContent='Unavailable';$('send').disabled=true}}
function weatherLabel(code){if(code===0)return 'Clear skies';if(code<4)return 'Partly cloudy';if(code<50)return 'Foggy';if(code<60)return 'Light drizzle';if(code<70)return 'Rain';if(code<80)return 'Snow';if(code<85)return 'Rain showers';if(code<90)return 'Snow showers';return 'Thunderstorms';}
async function refreshWeather(){try{const d=await api('weather');if(d.needsCity){$('weather-place').textContent='Your weather';$('weather-body').replaceChildren(node('p','Choose your city in Customize to see the weather here.','empty'));return}if(d.error)throw Error(d.error);$('weather-place').textContent=d.place;const temp=node('div',Math.round(d.current.temperature_2m)+'°','temperature');const desc=node('div',weatherLabel(d.current.weather_code),'weather-description');const detail=node('p','Feels like '+Math.round(d.current.apparent_temperature)+'° · Wind '+Math.round(d.current.wind_speed_10m)+' '+d.units.wind_speed_10m,'weather-details');const forecast=node('div',undefined,'forecast');d.daily.time.forEach((day,i)=>{const card=node('div');card.append(node('span',i===0?'TODAY':new Date(day+'T12:00:00').toLocaleDateString(undefined,{weekday:'short'}).toUpperCase()),node('b',Math.round(d.daily.temperature_2m_max[i])+'° / '+Math.round(d.daily.temperature_2m_min[i])+'°'));forecast.append(card)});$('weather-body').replaceChildren(temp,desc,detail,forecast);$('weather-time').textContent='Updated '+new Date(d.updated*1000).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});}catch(e){$('weather-body').replaceChildren(node('p',e.message,'empty'));$('weather-time').textContent='Could not update'}}
async function refreshNews(){ $('refresh-news').disabled=true;try{const d=await api('news');if(d.disabled){$('news-list').replaceChildren(node('p','Public headlines are switched off. You can enable them in Customize.','empty'));$('news-time').textContent='Offline preference';return}const links=d.items.map((item,i)=>{const a=node('a',undefined,'headline');a.href=item.url;a.target='_blank';a.rel='noopener noreferrer';const content=node('div');content.append(node('strong',item.title),node('small',item.source+' / '+date(item.published)));a.append(node('span',String(i+1).padStart(2,'0'),'number'),content,node('span','↗','arrow'));return a});$('news-list').replaceChildren(...(links.length?links:[node('p','Feeds are unavailable right now. Try again later.','empty')]));$('news-time').textContent='Checked '+new Date(d.updated*1000).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})+(d.errors.length?' · Unavailable: '+d.errors.join(', '):'')}catch(e){$('news-list').replaceChildren(node('p',e.message,'empty'))}finally{$('refresh-news').disabled=false}}
for(const el of document.querySelectorAll('[data-action]'))el.addEventListener('click',async()=>{el.disabled=true;try{await api('action',{action:el.dataset.action});toast('Opening '+({'resume':'your saved sessions','agent':'Codex','local-agent':'your local agent','files':'your projects','terminal':'a terminal','monitor':'the system monitor','artist':'ArtistOS'}[el.dataset.action])+'…')}catch(e){toast(e.message)}finally{el.disabled=false}});
async function openSettings(){try{config=await api('settings');$('city').value=config.city;$('units').value=config.units;$('news-enabled').checked=config.news;$('settings').showModal()}catch(e){toast(e.message)}}
for(const id of ['settings-open','customize','weather-settings','add-city'])$(id).addEventListener('click',openSettings);
$('settings-close').addEventListener('click',()=>$('settings').close());
$('settings-form').addEventListener('submit',async e=>{e.preventDefault();try{config=await api('settings',{city:$('city').value,units:$('units').value,news:$('news-enabled').checked});$('settings').close();toast('Preferences saved');refreshWeather();refreshNews()}catch(e){toast(e.message)}});
$('refresh-news').addEventListener('click',refreshNews);
function renderChat(){if(!history.length){$('messages').replaceChildren(node('p','Brainstorm, untangle an idea, or ask a question. This chat uses a local model and cannot run commands.','empty'));return}$('messages').replaceChildren(...history.map(m=>{const el=node('div',undefined,'message '+m.role);el.append(node('small',m.role==='user'?'YOU':'LOCAL MODEL'),document.createTextNode(m.content));return el}));$('messages').scrollTop=$('messages').scrollHeight;}
$('chat-form').addEventListener('submit',async e=>{e.preventDefault();const prompt=$('prompt').value.trim();if(!prompt||chatBusy)return;chatBusy=true;$('send').disabled=true;$('clear-chat').disabled=true;$('model').disabled=true;history.push({role:'user',content:prompt});renderChat();$('prompt').value='';$('chat-status').textContent='Thinking locally… CPU inference may take a moment.';try{const d=await api('chat',{model:$('model').value,messages:history.slice(-19)});history.push({role:'assistant',content:d.reply});renderChat();$('chat-status').textContent=d.tokens+' tokens · '+d.seconds+'s · computed on this machine'}catch(e){history.pop();renderChat();$('prompt').value=prompt;$('chat-status').textContent=e.message}finally{chatBusy=false;$('send').disabled=false;$('clear-chat').disabled=false;$('model').disabled=false}});
$('clear-chat').addEventListener('click',()=>{history=[];renderChat();$('chat-status').textContent='Chat cleared.'});
function saveFocus(){localStorage.setItem('quan-focus',JSON.stringify(focus))}
function tick(){const now=Date.now();$('clock').textContent=new Date().toLocaleString(undefined,{weekday:'short',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});let seconds=focus.end?Math.max(0,Math.ceil((focus.end-now)/1000)):focus.remaining;if(focus.end&&seconds===0){focus={remaining:0,end:null};saveFocus();toast('Focus session complete. Take a breath.');}$('timer').textContent=String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0');$('timer-toggle').textContent=focus.end?'Pause':seconds===0?'Start again':seconds===1500?'Start focus':'Continue';$('timer-label').textContent=focus.end?'YOU’VE GOT THIS':seconds===0?'TIME FOR A BREAK':'MAKE SOME SPACE';}
$('timer-toggle').addEventListener('click',()=>{if(focus.end){focus.remaining=Math.max(0,Math.ceil((focus.end-Date.now())/1000));focus.end=null}else{if(!focus.remaining)focus.remaining=1500;focus.end=Date.now()+focus.remaining*1000}saveFocus();tick()});
$('timer-reset').addEventListener('click',()=>{focus={remaining:1500,end:null};saveFocus();tick()});
$('focus-note').value=localStorage.getItem('quan-focus-note')||'';$('focus-note').addEventListener('input',()=>localStorage.setItem('quan-focus-note',$('focus-note').value));
window.addEventListener('resize',chart);tick();setInterval(tick,1000);refreshMachine();refreshModels();refreshWeather();refreshNews();setInterval(()=>{if(!document.hidden)refreshMachine()},5000);setInterval(()=>{if(!document.hidden)refreshModels()},15000);setInterval(refreshNews,1800000);setInterval(refreshWeather,900000);
